### ISSUE TITLE
need fill in text for Tessr Foundation on the Website.

### ISSUE THREAD

**Issue by davetlfl92** [tessr-labs/web#12]
this should fill in the first tab of "what is it?"     please adjust and edit as you see fit

what is crypto curriency?

A digital currency in which encryption techniques are used to regulate the generation of units of currency and verify the transfer of funds, operating independently of a central bank

What is an ICO?

ICO (Initial Coin Offering)  is a fundraising mechanism in which new projects sell their underlying crypto tokens in order build their project and achieve milestones.

How do I participate in an ICO?

In most cases, you can purchase the underlying token via their contract address in exchange for Bitcoin or Ethereum. Some ICOs will also accept some "Alt Coins" and or fiat curriency.

How do i benefit from buying in?

Cryptocurrinecy is treated as an asset. You will own the coin and can buy, sell or trade it. Its value is based on demand, token holders, fiat inflation and many other factors. Its works very similiarly to pennie stocks but in real time and more secure.

**Comment by davetlfl92** [comment]
ideas for the second tab "who are we"

What is the Tessr Foundation?

A foundation dedicated to teaching and improving the forever progressing developments of Arts and Technology! As the world moves closer towards the Blockchain Revolution, new doors open every day for technological and artistic advancements.
 
What does Tessr do?

Tessr is using blockchain technology and cryptocurriency to create an optimal and free secondary education system. A system that will be revolutionary to not only the students but instructors alike!

What sort of coarses will be offered?

Tessr will offer many courses across the board. Courses will include but not limited to  Technology development, Blockchain Tech Development, Arts, Music, Life Skills and many more!

What is the overall goal?

Tessr has a main goal to create a nationally supported education system. We want to build physical locations for in person instructions and maintain an even wider variety of online classes, all being powered and secured by the Tessr Blockchain Network.

**Comment by davetlfl92** [comment]
"How to get involved"

As a student?

We will have many ways you can enroll into our corses, such as in person classes at select locations and online web corses. All will be secure on the blockchain meaning in no way can your attence credits or test grades be lost. Your education is completely secure.

As a teacher?

As a teacher you will own the corses you teach. You can submit your coarse and cirriculum to the blockchain. Anyone who would want to attend your classes will have to go through your classes contract address and complete the requirements of the underlying contract

As a sponser?

You can contact Tessr at team@tessr.io to speak with us about your sponsership ideas. All proceeds that are paid to Tessr will be put directily into our donation pool to further our bring Tessr closer to its goal.
 
As a partner?

Tessr will be offering another token with dividens, this token will directly reflect your ownership of the Foundation. Contact us at team@tessr.io for more information on buying shares of the company
(TOTALLY JUST IDEAS) nothing written here has been confirmed by anyone, nor is it a solid idea in our adjenda

**Comment by SomtoTSRX** [comment]
Somto Edit 1
What is cryptocurrency?

A digital currency in which encryption techniques are used to regulate the generation of currency units,and verify the transfer of funds, all while operating independently of a central bank.

What is an ICO?
An ICO (Initial Coin Offering) is a fundraising mechanism used by new projects wherein they sell their underlying crypto tokens to the general public in order build their project and achieve milestones. IPO’s and ICO’s are very similar to one another IPOs are for stock’s, ICO’s are the crypto equivalent
 
How do I participate in an ICO?
In most cases, you can purchase the underlying token via a contract address in exchange for Bitcoin or Ethereum. Some ICOs will also accept certain"Alt Coins" and or fiat currency
 
How do i benefit from buying in?
Cryptocurrencies are treated as assets. By owning the coin one can buy sell or trade it. The value is determined by supply and demand,number of token holders, fiat inflation rate and many other factors.
 
What is the Tessr Foundation?
A foundation dedicated to teaching, improving and progressing the developments of Arts and Technology! As the world moves closer towards the Blockchain Revolution, new doors open every day for technological and societal advancements.
 
What does Tessr do?
Tessr is using blockchain technology as well as its own cryptocurrency to create an optimized and free secondary education system. A system that will be revolutionary for  not only the students but instructors alike!

What sort of courses will be offered?
Tessr will offer many courses across the board. Courses will include  Technology development, Blockchain Tech Development, Arts, Music, humanities, Life Skills and many more!
 
How to get involved"
As a student?
**see notes below**
 
As a teacher?
As a teacher you will always own the course content you teach on the platform. You can submit your courses and curriculum to the block-chain. Anyone who attends your classes will have to go through your class contract address and complete the requirements of the underlying contract,which you the teacher will create
 
As a sponsor?
You can contact Tessr at team@tessr.io to speak with us about your sponsorship idea/s. All proceeds that are paid to the Tessr foundation will be put directly into our donation pool to bring Tessr closer to its goal. (Note, donations and token purchases are not the same thing
 
As a partner?
 
 
****Notes****
 i think we should refrain and stay away from talking about bliding any physical classrooms and/or building. That is too far removed from our core competency, this is why  i did not include the student section. Also the last paragraph about partners needs to be taken out completely for several reasons

1.A foundation cannot have shareholders, only board members 2. Purchasing Tessrx tokens cannot have anything to do with the foundation. 3. For-profit companies pay dividends there is no way a dividend token can be used by a foundation. I understand that the paragraph is just ideas but we need a serious meeting about the foundation/educational aspect of this.

**Comment by tessr8** [comment]
I think we need to REMOVE any reference to ICO...

**Comment by davetlfl92** [comment]
The ICO parts were just added because they were already on the site. We should replace  it with crowdfunding information. Somto good call on the share holders. Was not familiar with that aspect on foundations

**Comment by davetlfl92** [comment]
who are we?
A collective dedicated to teaching and improving the forever progressing developments of  Technology! 
What does Tessr do?

Tessr is using blockchain technology  to create an optimal and free secondary education system. A system that will be revolutionary to not only the students but instructors alike!

What is Tessr's motivation?

Our motivation is to set in motion, an optimal education system that will empower students by giving them the knowledge to use and understand open source ideas. 

What is the overall goal?

Tessr has a main goal to create a internationally supported education system. One where educators own and develop their own coarses

change and edit as you see fit

**Comment by tessr8** [comment]
Issue closed ... Site update complete
